version: "3.9"
services:
  database:
    image: postgres
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      
  web:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/site_materialize
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/site_materialize/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - database

volumes:
  gem_cache:
  db_data:
  node_modules: